compatibility_date = "2022-05-12"
main = "src/index.ts"
name = "doh-cache-worker-cf"
send_metrics = false
usage_model = "bundled"

[vars]
DOH_ENDPOINT = "https://doh.pub/dns-query"
DOH_PATHNAME = "/dns-query"
